### ISSUE TITLE
White border on sides of search bar inside a note with dark mode

### ISSUE THREAD

**Issue by kryoqa** [Beaver-Notes/Beaver-pocket#24]
**Describe the bug**
White borders appear on both sides of search bar inside a note with dark mode enabled

**To Reproduce**
1. Open Beaver Pocket
2. Click on an existing note/ Create a new note
3. Click on search button at the top right of a note
4. Note search bar opens with white border on both ends

**Expected behavior**
The search bar should have dark borders or look similar to the main search option

**Screenshots**
![Screenshot_20241219-172311](https://github.com/user-attachments/assets/195f8e2a-4d13-4915-905b-8a6ce286236e)

**Smartphone (please complete the following information):**

 - OS: Android 14
 - Version [1.3.0]

**Comment by Daniele-rolli** [comment]
Thanks for your feedback! I'll address all three issues here since you opened them.

Regarding the border and autofocus issue, I’ve found and fixed it, I'll be pushing a commit ASAP. For #25, I’ll look into Google’s documentation. However, I’m not very familiar with Android or its design principles, so I’ll do my best.

As for #23, the themes are different because the components are different. The screenshots show components that use native Android elements, whereas the menu for adding a label or linking a note was custom written for that purpose.

Thanks for contributing to the project!
